### PR TITLE
Add GtkTrayIcon background patch

### PR DESCRIPTION
**Pull request by 9ary**
I came up with this patch which should be a lot more reliable than the previous one and good enough to be included in the AUR for now. I'll take it upstream and work with them to see how it can be cleaned up and merged.

### CODE REVIEW

**Comment by TomaszGasior** [comment]
I will look at this tomorrow.

**Comment by 9ary** [comment]
No rush, but I hope you haven't forgotten about this. :)

**Comment by TomaszGasior** [comment]
No, I am working on this **NOW**.  I will update package today. maybe after 00:00. ;) Sorry for long delay, I was busy on other projects.

**Comment by 9ary** [comment]
It's fine, thanks for taking a look. :+1:

**Comment by TomaszGasior** [comment]
https://github.com/TomaszGasior/gtk3-mushrooms/issues/12

**Pull request closed without merging**
